### ISSUE TITLE
Repeated messages not read correctly

### ISSUE THREAD

**Issue by mareksl** [ngx-grpc/core#1]
It seems that repeated messages are not handled correctly. (Or I am doing something wrong :smile: )

### Example code:
My .proto file:
```proto
service TodoService {
    rpc FindAll (TodoListRequest) returns (TodoList) {}
}

message TodoList {
    repeated Todo todos = 1;
}
```

 I'm getting the correct response from the server (tested with BloomRPC):
```json
{
    "todos": [
        {"id": 1, "name": "Buy Milk"},
        {"id": 2, "name": "Pay Bills"},
        {"id": 3, "name": "Play Games"}
    ]
}
```

However, I am getting this response from the TodoServiceClient:
![Screenshot from 2019-11-20 14-49-19](https://user-images.githubusercontent.com/21962147/69244408-32528680-0ba5-11ea-9f5d-506732ff2d51.png)

It looks as though it adds (and overwrites) the properties of the items to the array itself, and not to the individual items.
Any idea what might be going wrong / how to fix this?

**Comment by smnbbrv** [comment]
Hi there, we noticed the same today 🙂 please use the latest protocol plugin, it also contains a fix for the bytes fields. Please let me know if you still experience this behavior

**Comment by mareksl** [comment]
Yeah, saw the fix today actually, thanks!
Closing 🙂
